---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(workflows)
library(parsnip)
library(recipes)
library(yardstick)
library(glmnet)
library(tidyverse)
library(tidyquant)
library(timetk)
```

```{r}
bikes <- read_csv("Data/day.csv")

bikes_tbl <- bikes %>%
  select(dteday, cnt)%>%
  rename(date = dteday,
         value = cnt)

bikes_tbl%>%
  ggplot(aes(x = date, y = value))+
  geom_rect(xmin = as.numeric(ymd("2012-07-01")),
            xmax = as.numeric(ymd("2013-01-01")),
            ymin = 0, ymax = 10000,
            fill = palette_light()[[4]], alpha = 0.01)+
  annotate("text", x = ymd("2011-10-01"), y = 7800,
             color = palette_light()[[1]], label = "Train Region") +
  annotate("text", x = ymd("2012-10-01"), y = 1550,
             color = palette_light()[[1]], label = "Test Region") +
  geom_point(alpha = 0.5, color = palette_light()[[1]])
```

```{r}
# Split into training and test sets
train_tbl <- bikes_tbl %>% filter(date < ymd("2012-07-01"))
test_tbl  <- bikes_tbl %>% filter(date >= ymd("2012-07-01"))
```

```{r}
# add time series signature
recipe_spec_timeseries <- recipe(value ~ ., data = train_tbl)%>%
  step_timeseries_signature(date)

#prep and bake--apply the recipe to the dataset
bake(prep(recipe_spec_timeseries), new_data = train_tbl)%>%View()

#feature engineering
recipe_spec_final <- recipe_spec_timeseries%>%
  step_rm(date)%>%
  step_rm(contains("iso"),
          contains("second"), contains("minute"), contains("hour"),
          contains("am.pm"), contains("xts"))%>%
  step_normalize(contains("index.num"), date_year)%>%
  step_interact(~date_month.lbl * date_day)%>%
  step_interact(~date_month.lbl * date_mweek)%>%
  step_interact(~date_month.lbl * date_wday.lbl * date_yday)%>%
  step_dummy(contains("lbl"), one_hot = TRUE)

bake(prep(recipe_spec_final), new_data = train_tbl)
```

```{r}
#create model spec
model_spec_glmnet <- linear_reg(mode = 'regression', penalty = 10, mixture = 0.7)%>%
  set_engine('glmnet')
```

```{r}
#use workflows to join up recipe and model spec
workflow_glmnet <- workflow()%>%
  add_recipe(recipe_spec_final)%>%
  add_model(model_spec_glmnet)
```

```{r}
#train the workflow
workflow_trained <- workflow_glmnet%>%
  fit(data = train_tbl)
```

```{r}
#now to examine the forecast
prediction_tbl <- workflow_trained %>%
  predict(test_tbl)%>%
  bind_cols(test_tbl)

bikes_tbl%>%
  ggplot(aes(x = date))+
  geom_rect(xmin = as.numeric(ymd("2012-07-01")),
            xmax = as.numeric(ymd("2013-01-01")),
            ymin = 0, ymax = 10000,
            fill = palette_light()[[4]], alpha = 0.01)+
  annotate("text", x = ymd("2011-10-01"), y = 7800,
             color = palette_light()[[1]], label = "Train Region") +
  annotate("text", x = ymd("2012-10-01"), y = 1550,
             color = palette_light()[[1]], label = "Test Region") +
  geom_point(aes(x = date, y = value), alpha = 0.5, color = palette_light()[[1]])+
  # predictions
  geom_point(aes(x = date, y = .pred), data = prediction_tbl,
             alpha = 0.5, color = palette_light()[[2]])+
  theme_tq()+
  labs(title = "GLM: Out-of-Sample Forecast")
```

```{r}
#validation accuracy(out of sample) measured with yardstick

#forecast error
prediction_tbl%>%
  metrics(value, .pred)
```

```{r}
#looking at residuals
prediction_tbl%>%
  ggplot(aes(x = date, y = value - .pred))+
  geom_hline(yintercept = 0, color = 'black')+
  geom_point(color = palette_light()[[1]], alpha = .5)+
  geom_smooth(span = 0.05, color = 'red')+
  geom_smooth(span = 1, se = FALSE, color = 'blue')+
  theme_minimal()+
  scale_y_continuous(limits = c(-5000, 5000))
```


```{r}
#forecasting future data

# extract bike indexes
idx <- bikes_tbl%>%
  tk_index()

# time series summary from index
bikes_summary <- idx%>%
  tk_get_timeseries_summary()

idx_future <- idx %>%
  tk_make_future_timeseries(n_future = 180)

future_tbl <- tibble(date = idx_future)

# retrain model spec on the full dataset then predict on this future 6 months
future_predictions_tbl <- workflow_glmnet %>%
  fit(data = bikes_tbl)%>%
  predict(future_tbl)%>%
  bind_cols(future_tbl)
  
```

```{r}
#visualize forecast
bikes_tbl %>%
    ggplot(aes(x = date, y = value)) +
    geom_rect(xmin = as.numeric(ymd("2012-07-01")),
              xmax = as.numeric(ymd("2013-01-01")),
              ymin = 0, ymax = 10000,
              fill = palette_light()[[4]], alpha = 0.01) +
    geom_rect(xmin = as.numeric(ymd("2013-01-01")),
              xmax = as.numeric(ymd("2013-07-01")),
              ymin = 0, ymax = 10000,
              fill = palette_light()[[3]], alpha = 0.01) +
    annotate("text", x = ymd("2011-10-01"), y = 7800,
             color = palette_light()[[1]], label = "Train Region") +
    annotate("text", x = ymd("2012-10-01"), y = 1550,
             color = palette_light()[[1]], label = "Test Region") +
    annotate("text", x = ymd("2013-4-01"), y = 1550,
             color = palette_light()[[1]], label = "Forecast Region") +
    geom_point(alpha = 0.5, color = palette_light()[[1]]) +
    # future data
    geom_point(aes(x = date, y = .pred), data = future_predictions_tbl,
               alpha = 0.5, color = palette_light()[[2]]) +
    geom_smooth(aes(x = date, y = .pred), data = future_predictions_tbl,
                method = 'loess') + 
    labs(title = "Bikes Sharing Dataset: 6-Month Forecast", x = "") +
    theme_minimal()
```

```{r}
#calculating prediction intervals for the model predictions

#calculate standard deviation of residuals
test_resid_sd <- prediction_tbl %>%
  summarise(stdev = sd(value - .pred))

future_predictions_tbl <- future_predictions_tbl%>%
  mutate(
    lo.95 = .pred - 1.96 * test_resid_sd$stdev,
    lo.80 = .pred - 1.28 * test_resid_sd$stdev,
    hi.95 = .pred + 1.96 * test_resid_sd$stdev,
    hi.80 = .pred + 1.28 * test_resid_sd$stdev,
  )

bikes_tbl %>%
  ggplot(aes(x = date, y = value))+
  geom_point(alpha = 0.5, color = palette_light()[[1]])+
  geom_ribbon(aes(y = .pred, ymin = lo.95, ymax = hi.95),
              data = future_predictions_tbl, fill = "#D5DBFF",
              color = NA, size = 0)+
  geom_ribbon(aes(y = .pred, ymin = lo.80, ymax = hi.80, fill = key),
              data = future_predictions_tbl, fill = "#596DD5",
              color = NA, size = 0, alpha = .8)+
  geom_point(aes(x = date, y = .pred), data = future_predictions_tbl,
             alpha = 0.5, color = palette_light()[[2]])+
  geom_smooth(aes(x = date, y = .pred), data = future_predictions_tbl,
              method = 'loess', color = 'white')+
  labs(title = "Bikes Sharing Dataset: 6-Month Forecast with Prediction Intervals", x = "") +
  theme_minimal()
```

